# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdBRUlbcZtl8VNvnczMaPtjKzxxJVwbU
"""

listx = [20, 100, 35, 40, 120, 46]
print(listx)
 
tuplex = tuple(listx)
print(tuplex)