# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdBRUlbcZtl8VNvnczMaPtjKzxxJVwbU
"""

num = {'Anil': 80, 'Kiran': 90, 'Charan': 86, 'Mahesh' :56}
print(list(num)[3])