# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdBRUlbcZtl8VNvnczMaPtjKzxxJVwbU
"""

tuple2 = ('python', '41', 'Colab', True, 5.3) 
 
print(len(tuple2))