# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdBRUlbcZtl8VNvnczMaPtjKzxxJVwbU
"""

tup1 = (4 ,6, 8, 10) 
 
print(tup1[1:]) 
 
print(tup1[::-1]) 
 
print(tup1[1:3])