# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uCbE7CeOUbexAAPi9oKiUk4Czihw5xpZ
"""

def Reverse(tuples): 
 
    new_tup = tuples[::-1] 
 
    return new_tup 
 
      
 
tuples = ('6','9','12','15','18','21','24','27') 
 
print(Reverse(tuples))