# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYRD9o6DTd5UI0j7ySetSUyBO9R_wz9E
"""

my_dict = {'x':300,'y':-34,'z':250}
print(sum(my_dict.values()))