# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdBRUlbcZtl8VNvnczMaPtjKzxxJVwbU
"""

def convertTuple(tup): 
 
    str =  ''.join(tup) 
 
    return str
 
 
 
tuple = ('A', 'n', 'i', 'l', 'K','u', 'm', 'a', 'r' ) 
 
str = convertTuple(tuple) 
 
print(str)