# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdBRUlbcZtl8VNvnczMaPtjKzxxJVwbU
"""

d = {'Orange': 4, 'Yellow ': 3, 'White': 6} 
for color_key, value in d.items():
     print(color_key, 'corresponds to ', d[color_key])

